uber/aresdb

client/connector.go, memstore/common/upsert_batch_builder.go, memstore/common/upsert_batch_builder_test.go, memstore/common/upsert_batch_header.go, memstore/redo_log_browser_test.go, memstore/upsert_batch.go, memstore/upsert_batch_test.go, utils/stream_serialization.go, utils/stream_serialization_test.go
add version number to upsert batch
and update upsert batch format to include arrival time
=> Update upsert batch version

query/algorithm.h, query/algorithm_unittest.cu, query/aql_compiler.go, query/aql_compiler_test.go, query/aql_processor.go, query/aql_processor_test.go, query/geo_intersects.cu, query/time_series_aggregate.go, query/time_series_aggregate.h
Right now for geo join, we keep null geo dim values which is redundant and confusing. We need to remove those rows so that result won't contain null dim value
=> filter out null geo dim

client/connector.go, memstore/archiving_test.go, memstore/common/upsert_batch_builder.go, memstore/common/upsert_batch_builder_test.go, memstore/ingestion_test.go, memstore/redo_log_manager_test.go, memstore/upsert_batch_test.go
=> use new upsert batch format and allow missing time in client

.travis.yml
=> config travis only to build on pushed commits on master

api/debug_handler_test.go, memstore/archive_store.go, memstore/archive_store_test.go, memstore/backfill_test.go, memstore/batch.go, memstore/host_memory_manager_test.go, memstore/json_marshaller_test.go, memstore/live_store.go, memstore/merge.go, memstore/merge_test.go, memstore/table_shard_test.go, memstore/test_factory.go, query/aql_processor_test.go, query/device_manager_test.go
=> copy lock when over when creating new batch

client/connector.go
Hi! Seems checking of length can be fixed since it can't be negative
=> Fix checking of length

Makefile, query/aql_postprocessor.go, query/sort_reduce.cu
for sort and reduce this time. but we can apply it to all other functions
=> Use local macro to reduce redundant code

api/schema_handler.go, api/schema_handler_test.go, glide.lock, glide.yaml, memstore/host_memory_manager_test.go, metastore/common/model.go, metastore/disk_metastore.go, metastore/disk_metastore_test.go, metastore/error.go, metastore/validator.go, metastore/validator_test.go
=> provide default table configs

api/ui/debug/archive.html, api/ui/debug/backfill.html, api/ui/debug/memory.html, api/ui/debug/purge.html, api/ui/debug/redologs.html, api/ui/debug/snapshot.html, api/ui/package.json
we are including "datatables.net-dt" in the package json which is incorrect. We should include datatables.net
=> fix data table in debug ui

.gitignore, memstore/archiving_test.go, memstore/common/data_type.go, memstore/host_memory_manager_test.go, memstore/ingestion.go, memstore/merge_test.go, memstore/test_factory.go, memstore/upsert_batch.go, query/algorithm.hpp, query/algorithm_unittest.cu, query/aql.go, query/aql_batchexecutor.go, query/aql_compiler.go, query/aql_context.go, query/aql_nonaggr_batchexecutor.go, query/aql_postprocessor.go, query/aql_processor.go, query/aql_processor_test.go, query/common/aql_query_result.go, query/common/aql_query_result_test.go, query/hll.cu, query/hll.go, query/iterator.hpp, query/iterator_unittest.cu, query/sort_reduce.cu, query/stats.go, query/time_series_aggregate.go, query/time_series_aggregate.h, testing/data/batches/archiving/archiveBatch1, testing/data/vps/archiving/sortedVP00
will add more test cases for go part
=> non-aggregation query support

gateway/controller.go, gateway/controller_test.go
currently a new header value is added to headers after each `buildRequest` call.
=> fix headers bug

memutils/memory/rmm_alloc.cu
DeviceFree frees wrong pointer, use the passed in arguments
=> free correct pointer

query/aql_processor.go
=> fix archivestore lock issue

client/connector.go, client/connector_test.go, client/schema.go
extract schema and enum logic
SchemaFetcher is pluggable
=> refactor connector

memstore/common/vector_party.go, memstore/vector_party.go, memstore/vector_party_test.go, query/aql_processor_test.go
when slideIndex, the last range of upperbound/lowerbound should be vp.length + 1
=> fix pre filter problem

query/aql_batchexecutor.go, query/aql_processor.go, query/aql_processor_test.go
recreate to trigger travis build
=> fix query panic when no non-pre filter is present

api/query_handler.go, api/query_handler_test.go, api/sql_query_handler.go, query/aql_batchexecutor.go, query/aql_compiler.go, query/aql_context.go, query/aql_nonaggr_batchexecutor.go, query/aql_postprocessor.go, query/aql_postprocessor_test.go, query/aql_processor.go, query/aql_processor_test.go, query/common/aql_query_result_test.go, query/stats.go, utils/metrics.go
this will reduce TTFB for non-agg queries from 10+s to milliseconds.
=> eager flush results for single non aggregate query

memstore/archiving.go, memstore/backfill.go, memstore/purge.go, memstore/scheduler.go, memstore/snapshot.go, memstore/snapshot_test.go, utils/metrics.go
so it doesn't crash the server.
=> recover from job panic

metastore/disk_metastore_test.go
increase metastore test coverage
=> metastore test coverage

CMakeLists.txt, controller/cluster/etcd.go, go.mod, subscriber/common/job/controller.go
Also, fix some m3x path issues
=> upgrade m3db to 0.9.5

.gitignore, api/response.go, memstore/host_memory_manager_test.go, query/aql_nonaggr_batchexecutor.go, query/sql_parser.go, query/sql_parser_test.go
- fix sql parser populating LIMIT
- fix result flushing
=> fix non agg query

broker/broker_suite_test.go, broker/common/constant.go, broker/common/types.go, broker/executor.go, broker/handler.go, broker/query_plan.go, broker/result_merge.go, broker/result_merge_test.go, broker/schema_manager.go, query/aql.go, query/aql_compiler.go, query/aql_compiler_test.go
- refactor interfaces to common pkg
- add query plan, define plan nodes
- implement resultMerge logic
=> add merge node

client/schema.go, controller/client/controller.go, controller/mutators/etcd/job_mutator.go, controller/mutators/etcd/job_mutator_test.go, controller/mutators/etcd/namespace_mutator.go, controller/tasks/etcd/ingestion_assignment_test.go
1. controller recent change: job version
2. bug fixes: namespace mutator capture non exist error to return empty list
3. ExtendEnumCases should not make http call when no enum cases
=> controller recent changes

common/config.go, datanode/datanode.go, memstore/recovery_test.go, redolog/composite_redolog_manager.go, redolog/composite_redolog_manager_test.go, redolog/kafka_redolog_manager.go, redolog/kafka_redolog_manager_test.go, redolog/redolog_manager_master.go, utils/kafka.go
=> update config for distributed test

cmd/aresd/cmd/cmd.go, datanode/bootstrap.go, datanode/bootstrap/bootstrap_server.go, datanode/bootstrap/bootstrap_server_bm_test.go, datanode/datanode.go, memstore/bootstrap.go, memstore/memstore.go, metastore/disk_metastore.go, metastore/disk_metastore_test.go
1. remove hard coded shard 0 pre-creation, instead use MkdirAll before all file writes
2. remove shard checking in MetaStore. metastore does not check for shard ownership anymore
3. fix AssignShardSet bug
4. add missing etcd client creation
=> Fix datanode

api/debug_handler.go, api/debug_handler_test.go, api/ui/debug/js/batch.js, api/ui/debug/js/summary.js, cmd/aresd/cmd/cmd.go, datanode/datanode.go
remove hard coded shard 0 in debug ui
=> remove hard coded shard 0 in debug ui

broker/query_plan_agg.go, broker/query_plan_agg_test.go, broker/query_plan_non_agg_test.go
make copy of query to avoid appending to same shard list
=> fix sub query gen

broker/query_compiler.go, broker/query_compiler_test.go, broker/query_plan_non_agg.go, broker/query_plan_non_agg_test.go
- implement LIMIT support for non-agg query
- column wildcard expansion in broker
=> [broker] support limit and fix header issue

cmd/aresd/cmd/cmd.go, cmd/broker/cmd/cmd.go, query/aql_compiler.go, query/aql_compiler_test.go, query/aql_processor_test.go, query/time_bucketizer_test.go, utils/di.go, utils/metrics.go, utils/metrics_test.go
to enable different components initial only subset of metrics
=> refactor metrics

datanode/bootstrap.go, datanode/datanode.go, datanode/peer_source.go, memstore/bootstrap.go, utils/http.go
1. h2c to use http2 without TLS
2. missing SessionID and NodeID in peer streaming requests
3. initialize peer source
4. strip http:// from host address in grpc call
tested node replacement operation locally with controller and 3 initial data nodes
=> fix bugs in bootstrap process

datanode/bootstrap.go, datanode/bootstrap/types.go, datanode/datanode.go, datanode/options.go, datanode/peer_source.go, datanode/types.go, memstore/bootstrap.go, memstore/memstore.go, memstore/mocks/MemStore.go, memstore/table_shard.go
1. handle dimension table bootstrap
2. handle table addition event
3. clean up logging and bug fix
=> new shard on schema change

cmd/aresd/cmd/cmd.go, datanode/datanode.go, datanode/datanode_test.go, datanode/types.go, memstore/bootstrap.go
1. bootstrap non initializing (available and leaving) shards first
2. on server start, only wait for non initializing shards readiness
=> bootstrap non-initializing shard first

api/ui/debug/bootstrap.html, api/ui/debug/index.html, api/ui/debug/js/bootstrap.js, api/ui/debug/js/utils.js
initial bootstrap debug ui page
next:
1. source
2. start time
3. column (vector party) level tracking
=> initial ui for bootstrap details tracking

cluster/topology/healthtracking_dynamic.go, cluster/topology/healthtracking_dynamic_test.go, cluster/topology/types.go, cmd/broker/cmd/cmd.go
- add HealthTrackingDynamicTopology
- move topology interfaces to common
next: mark host healhiness in broker
=> add health checking topology

query/aql_context.go, query/aql_postprocessor.go, query/aql_postprocessor_test.go, query/aql_processor_test.go
- fix extra comma when actual results < limit
- fix null value representation
=> fix non-agg

broker/query_plan_agg.go, broker/query_plan_agg_test.go, broker/query_plan_non_agg.go, broker/query_plan_non_agg_test.go, broker/util/assignment.go, broker/util/assignment_test.go, cluster/topology/healthtracking_dynamic_test.go, datanode/bootstrap/bootstrap_server_test.go, datanode/client/query_client.go, datanode/client/query_client_test.go
- fix assignment bug
- abort query execution on context cancellations
=> fix broker non agg query execution

.travis.yml, datanode/bootstrap/bootstrap_server_test.go, memstore/backfill_test.go, memstore/common/data_value.go, memstore/common/data_value_test.go, memstore/common/upsert_batch_test.go, memstore/list/archive_vector_party.go, memstore/list/archive_vector_party_test.go, memstore/list/live_vector_party.go, memstore/list/live_vector_party_test.go, memstore/list/test_factory_test.go, memstore/list/vector_party.go, query/aql_processor_array_test.go, query/functor_unittest.cu, query/iterator.hpp, query/iterator_unittest.cu
=> Array support null value

api/debug_handler.go, api/debug_handler_test.go, broker/broker_schema_mutator.go, client/connector.go, client/connector_test.go, client/schema.go, controller/mutators/etcd/enum_mutator.go, controller/mutators/etcd/schema_mutator.go, memstore/list/archive_vector_party.go, memstore/list/archive_vector_party_test.go, memstore/list/live_vector_party.go, memstore/list/live_vector_party_test.go, memstore/list/vector_party.go, memstore/schema.go, metastore/common/ares_suite_test.go, metastore/common/model.go, metastore/common/model_test.go, metastore/disk_metastore.go, metastore/schema_fetch.go
- enum array client ingestion support
- enum array debug batch display
=> Array enum client

datanode/datanode.go, memstore/bootstrap.go, memstore/bootstrap_test.go, memstore/memstore.go, memstore/mocks/MemStore.go, metastore/common/types.go, metastore/disk_metastore.go, metastore/mocks/metastore.go
before adding new table shard and after removing table shard
=> purge metastore and diskstore table shard data
